include ../../../../../internal/setup/CommonVariables.mk
include ../../../../../internal/setup/ServiceCommon.mk
include ../../../../../internal/setup/BaseService.mk

DOMAIN_NAME = nutrition
SERVICE_NAME = personal_nutrition_lifestyle

SERVICE_PORT = 20004
