apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: mongodb-ns
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo