apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb-persistent-volume-claim
  name: mongodb-persistent-volume-claim
  namespace: mongodb-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi