apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: mongodb-ns
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-ext-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=