---
apiVersion: v1
kind: Service
metadata:
  name: nutrition-service
  namespace: default
  labels:
    app: nutrition-server
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: nutrition-server
  type: LoadBalancer