version: '3.9'
services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    volumes:
      - './db:/data/db'
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=custom_username
      - MONGO_INITDB_ROOT_PASSWORD=custom_password
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=custom_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=custom_password
      - ME_CONFIG_MONGODB_URL=mongodb://custom_username:custom_password@db:27017/
    depends_on:
      - db