services:
  nutrition-service:
    image: ${AGGREGATION_SERVICE_NAME}
    container_name: ${AGGREGATION_SERVICE_NAME}
    environment:
      - SERVICE_PORT=${AGGREGATION_SERVICE_PORT}
      - MONGODB_IP=${MONGODB_IP}
      - MONGODB_PORT=${MONGODB_PORT}
    expose:
      - ${AGGREGATION_SERVICE_PORT}
    ports:
      - ${PUBLISHED_AGGREGATION_SERVICE_PORT}:${AGGREGATION_SERVICE_PORT}
    networks:
      - mongodb-network

networks:
  mongodb-network:
    external: true