include ../../internal/setup/ServiceCommon.mk
include ../../internal/setup/DomainCommon.mk

RELATIVE_PATH_TO_ROOT = ../..

# TODO construct DOMAIN_NAME and SERVICE_NAME with assumptions that this file is in the base service root dir
# Every Makefile for now will have custom variables DOMAIN_NAME and SERVICE_NAME
SERVICE_CONTAINER_NAME = $(DOMAIN_NAME)-service

DOMAIN_NAME=nutrition
