services:
  nutrition-storage-mongo:
    image: mongo:latest
    attach: false
    container_name: nutrition-storage-mongo-container
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 60s
      retries: 5
    ports:
      - 27017:27017
    volumes:
      - nutrition-volume-mongo:/data/db
    networks:
      - nutrition-network-int

  nutrition-storage-mongo-observer:
    image: mongo-express:latest
    attach: false
    container_name: nutrition-storage-mongo-observer-container
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=nutrition-storage-mongo
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - nutrition-network-int
    depends_on:
      nutrition-storage-mongo:
        condition: service_healthy

  nutrition-message-broker-rabbitmq:
    build:
      context: ./worker/mq
      dockerfile: ./message-broker-rabbitmq.Dockerfile
    container_name: nutrition-message-broker-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 20s
      retries: 3
    ports:
    - 15672:15672 # http for an easy overview of mq statistics
    - 5672:5672 # amqp for an actual messages propagation
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - nutrition-network-int

  nutrition-worker:
    image: nutrition-worker
    container_name: nutrition-worker
    environment:
      - MONGODB_IP=nutrition-storage-mongo
      - MONGODB_PORT=27017
    networks:
      - nutrition-network-int
    depends_on:
      nutrition-message-broker-rabbitmq:
        condition: service_healthy
      nutrition-storage-mongo:
        condition: service_healthy

  nutrition-service:
    image: nutrition-service
    container_name: nutrition-service
    environment:
      - SERVICE_PORT=50001
      - MONGODB_IP=nutrition-storage-mongo
      - MONGODB_PORT=27017
    ports:
      - 50001:50001
    networks:
      - nutrition-network-int
    depends_on:
      nutrition-message-broker-rabbitmq:
        condition: service_healthy
      nutrition-storage-mongo:
        condition: service_healthy

volumes:
  nutrition-volume-mongo:

networks:
  nutrition-network-int:
  nutrition-ext-network:
    external: true