include ../../../../../internal/setup/CommonVariables.mk
include ../../../../../internal/setup/ServiceCommon.mk
include ../../../../../internal/setup/BaseService.mk

DOMAIN_NAME = users
SERVICE_NAME = auth
