include ../../../../../internal/setup/CommonVariables.mk
include ../../../../../internal/setup/ServiceCommon.mk
include ../../../../../internal/setup/BaseService.mk

DOMAIN_NAME = nutrition
SERVICE_NAME = recipe

SERVICE_PORT = 20002
