include ../../../../../internal/setup/CommonVariables.mk
include ../../../../../internal/setup/ServiceCommon.mk
include ../../../../../internal/setup/BaseService.mk

DOMAIN_NAME = security
SERVICE_NAME = auth
SERVICE_PORT = 10001
