include ../../../../../internal/setup/CommonVariables.mk
include ../../../../../internal/setup/ServiceCommon.mk
include ../../../../../internal/setup/BaseService.mk

DOMAIN_NAME = nutrition
SERVICE_NAME = ingredient

run:
	go run -mod=mod ./*